apiVersion: v1
kind: Service
metadata:
  name: ai-video-generator-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 7860
    protocol: TCP
  selector:
    app: ai-video-generator 